[package]
name = "gradient_decent_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"

Random = {package = "rand", version = "0.8.5"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mnist = "0.6.0"
rayon = "1.10.0"
image = "0.25.5"
imageproc = "0.25.0"
